package io.airlab.kafbat.serde.asterix.category;

import io.airlab.kafbat.serde.asterix.spec.SpecLoader;

import java.util.HashMap;
import java.util.Map;

/**
 * Registry of known ASTERIX {@link CategoryDefinition}s.
 *
 * <p>{@link #withBuiltins()} first loads all categories from the bundled JSON
 * specs generated by {@code tools/update-specs.py}, then falls back to the
 * hand-written definitions for CAT002/010/021/034/048 if the specs are missing.
 * Additional categories can be registered at runtime via {@link #register}.
 */
public class CategoryRegistry {

    private final Map<Integer, CategoryDefinition> definitions = new HashMap<>();

    /**
     * Creates a registry populated from the bundled JSON specs (all 27+ categories,
     * all latest editions).  Hand-written definitions are used as fallback when no
     * spec file is present (e.g. during development before running update-specs.py).
     */
    public static CategoryRegistry withBuiltins() {
        // Load from generated specs first
        CategoryRegistry r = SpecLoader.loadAll();

        // Fallback: register hand-written definitions for core categories
        // if the spec loader did not already cover them.
        if (!r.contains(2))   r.register(Cat002.definition());
        if (!r.contains(10))  r.register(Cat010.definition());
        if (!r.contains(21))  r.register(Cat021.definition());
        if (!r.contains(34))  r.register(Cat034.definition());
        if (!r.contains(48))  r.register(Cat048.definition());
        return r;
    }

    /** Register (or replace) a category definition. */
    public void register(CategoryDefinition def) {
        definitions.put(def.category, def);
    }

    /**
     * Look up a category definition by number.
     *
     * @return the definition, or {@code null} if the category is unknown
     */
    public CategoryDefinition get(int category) {
        return definitions.get(category);
    }

    /** Returns {@code true} if this registry knows about {@code category}. */
    public boolean contains(int category) {
        return definitions.containsKey(category);
    }
}
