package io.airlab.kafbat.serde.asterix;

import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import io.airlab.kafbat.serde.asterix.category.CategoryDefinition;
import io.airlab.kafbat.serde.asterix.category.CategoryRegistry;
import io.airlab.kafbat.serde.asterix.parser.AsterixParser;
import io.airlab.kafbat.serde.asterix.spec.SpecLoader;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.*;

/**
 * Tests for spec-driven loading via {@link SpecLoader}.
 *
 * <p>These tests verify that the bundled JSON specs (generated by
 * {@code tools/update-specs.py}) are parsed correctly and that the
 * resulting {@link CategoryDefinition}s can decode real ASTERIX binary
 * messages.
 */
class SpecLoaderTest {

    // -----------------------------------------------------------------------
    // Registry population
    // -----------------------------------------------------------------------

    @Test
    void loadAll_populatesRegistryWithBundledSpecs() {
        CategoryRegistry registry = SpecLoader.loadAll();

        // Core categories that must always be present
        assertThat(registry.contains(2)).isTrue();
        assertThat(registry.contains(34)).isTrue();
        assertThat(registry.contains(48)).isTrue();
    }

    @Test
    void loadAll_cat048_hasExpectedItemCount() throws Exception {
        // Load the latest CAT048 spec directly
        CategoryDefinition def = SpecLoader.loadSpec("asterix-specs/cat048/1.32.json");

        assertThat(def).isNotNull();
        assertThat(def.category).isEqualTo(48);
        assertThat(def.name).isNotBlank();
        // UAP must reference standard items (at minimum I010, I140, I040)
        assertThat(def.uap).contains("I010", "I140", "I040");
    }

    @Test
    void loadAll_cat002_hasExpectedItems() throws Exception {
        CategoryDefinition def = SpecLoader.loadSpec("asterix-specs/cat002/1.2.json");

        assertThat(def).isNotNull();
        assertThat(def.category).isEqualTo(2);
        assertThat(def.uap).contains("I010", "I000");
    }

    @Test
    void loadSpec_unknownResource_returnsNull() throws Exception {
        assertThat(SpecLoader.loadSpec("asterix-specs/catXXX/9.9.json")).isNull();
    }

    // -----------------------------------------------------------------------
    // Spec-driven parsing – CAT048
    // -----------------------------------------------------------------------

    /**
     * Verify that a spec-loaded CAT048 definition produces the same output as
     * the hand-written parser for a basic position record.
     *
     * <pre>
     * Header: 30 00 0D        CAT=48, LEN=13
     * FSPEC:  D0              I010(bit7), I140(bit6), I040(bit4); FX=0
     * I010:   00 01           SAC=0, SIC=1
     * I140:   46 50 00        ToD = 0x465000 / 128 = 36000.0 s (10:00:00 UTC)
     * I040:   64 00 40 00     RHO = 25600 / 256 = 100.0 NM, THETA = 16384*360/65536 = 90.0°
     * </pre>
     */
    @Test
    void specDriven_cat048_basicPosition() {
        // Build registry exclusively from bundled specs (no hand-written fallback)
        CategoryRegistry registry = SpecLoader.loadAll();
        AsterixParser parser = new AsterixParser(registry);

        byte[] msg = {
            0x30, 0x00, 0x0D,
            (byte) 0xD0,              // FSPEC: I010 (bit7), I140 (bit6), I040 (bit4)
            0x00, 0x01,
            0x46, 0x50, 0x00,
            0x64, 0x00, 0x40, 0x00
        };

        ArrayNode result = parser.parse(msg);
        assertThat(result).hasSize(1);
        assertThat(result.get(0).get("category").asInt()).isEqualTo(48);

        ObjectNode record = (ObjectNode) result.get(0).get("records").get(0);

        assertThat(record.get("I010").get("SAC").asInt()).isEqualTo(0);
        assertThat(record.get("I010").get("SIC").asInt()).isEqualTo(1);
        // I140 is an Element Quantity, wrapped to {"val": <seconds>}
        assertThat(record.get("I140").get("val").asDouble()).isCloseTo(36000.0, within(0.01));
        assertThat(record.get("I040").get("RHO").asDouble()).isCloseTo(100.0, within(0.01));
        assertThat(record.get("I040").get("THETA").asDouble()).isCloseTo(90.0, within(0.01));
    }

    // -----------------------------------------------------------------------
    // Spec-driven parsing – CAT002
    // -----------------------------------------------------------------------

    @Test
    void specDriven_cat002_northMarker() {
        CategoryRegistry registry = SpecLoader.loadAll();
        AsterixParser parser = new AsterixParser(registry);

        byte[] msg = {
            0x02, 0x00, 0x07,
            (byte) 0xC0,
            0x00, 0x01,
            0x01
        };

        ArrayNode result = parser.parse(msg);
        assertThat(result).hasSize(1);
        assertThat(result.get(0).get("category").asInt()).isEqualTo(2);

        ObjectNode record = (ObjectNode) result.get(0).get("records").get(0);
        assertThat(record.get("I010").get("SAC").asInt()).isEqualTo(0);
        assertThat(record.get("I010").get("SIC").asInt()).isEqualTo(1);
        // I000 Message Type = 1 (North Marker) – spec parser may encode as raw or table
        assertThat(record.has("I000")).isTrue();
    }

    // -----------------------------------------------------------------------
    // withBuiltins fallback behaviour
    // -----------------------------------------------------------------------

    /**
     * CategoryRegistry.withBuiltins() must load specs first, then fall back to
     * hand-written definitions only for categories not covered by specs.
     */
    @Test
    void withBuiltins_specCategoriesTakePrecedence() {
        CategoryRegistry registry = CategoryRegistry.withBuiltins();

        // Categories covered by specs: definitions should come from SpecLoader
        assertThat(registry.contains(48)).isTrue();
        assertThat(registry.contains(34)).isTrue();
        assertThat(registry.contains(21)).isTrue();

        // Registry must also include categories that are only hand-written
        // (if any remain after spec loading)
        assertThat(registry.contains(10)).isTrue();
    }

    // -----------------------------------------------------------------------
    // Multi-category message after spec loading
    // -----------------------------------------------------------------------

    @Test
    void specDriven_mixedCategories_parsedIndependently() {
        CategoryRegistry registry = SpecLoader.loadAll();
        AsterixParser parser = new AsterixParser(registry);

        // CAT002 north marker followed by CAT048 basic position
        byte[] cat2  = { 0x02, 0x00, 0x07, (byte)0xC0, 0x00, 0x01, 0x01 };
        byte[] cat48 = { 0x30, 0x00, 0x0D, (byte)0xD0,  // I010+I140+I040
                         0x00, 0x01, 0x46, 0x50, 0x00, 0x64, 0x00, 0x40, 0x00 };
        byte[] combined = new byte[cat2.length + cat48.length];
        System.arraycopy(cat2,  0, combined, 0,           cat2.length);
        System.arraycopy(cat48, 0, combined, cat2.length, cat48.length);

        ArrayNode result = parser.parse(combined);
        assertThat(result).hasSize(2);
        assertThat(result.get(0).get("category").asInt()).isEqualTo(2);
        assertThat(result.get(1).get("category").asInt()).isEqualTo(48);
    }

    // Helper to make within() work without a static import conflict
    private static org.assertj.core.data.Offset<Double> within(double d) {
        return org.assertj.core.data.Offset.offset(d);
    }
}
